from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, Protocol, TypedDict, overload

if TYPE_CHECKING:
    from pyon.core import DOMElement, DOMTextNode

class ScreenOrientation(Protocol):
    """Protocol representing screen orientation in the browser."""
    @property
    def type(self) -> str: ...
    @property
    def angle(self) -> int: ...
    def lock(self, orientation: str) -> Any: ...
    def unlock(self) -> None: ...
    def addEventListener(self, event: str, callback: Any) -> None: ...
    def removeEventListener(self, event: str, callback: Any) -> None: ...

class Screen(Protocol):
    """Protocol for the browser's Screen object (e.g. window.screen)."""
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...
    @property
    def availWidth(self) -> int: ...
    @property
    def availHeight(self) -> int: ...
    @property
    def colorDepth(self) -> int: ...
    @property
    def pixelDepth(self) -> int: ...
    @property
    def orientation(self) -> ScreenOrientation: ...

class VisualViewport(Protocol):
    """Protocol for the VisualViewport object."""
    @property
    def offsetLeft(self) -> float: ...
    @property
    def offsetTop(self) -> float: ...
    @property
    def pageLeft(self) -> float: ...
    @property
    def pageTop(self) -> float: ...
    @property
    def width(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def scale(self) -> float: ...
    def addEventListener(self, event: str, callback: Any) -> None: ...
    def removeEventListener(self, event: str, callback: Any) -> None: ...

class MediaQueryList(Protocol):
    """Protocol for the MediaQueryList object."""
    @property
    def matches(self) -> bool: ...
    @property
    def media(self) -> str: ...
    def addEventListener(self, event: str, callback: Any) -> None: ...
    def removeEventListener(self, event: str, callback: Any) -> None: ...
    def addListener(self, callback: Any) -> None: ...
    def removeListener(self, callback: Any) -> None: ...

class Storage(Protocol):
    """Protocol for the Web Storage API (localStorage / sessionStorage)."""
    @property
    def length(self) -> int: ...
    def key(self, index: int) -> str | None: ...
    def getItem(self, key: str) -> str | None: ...
    def setItem(self, key: str, value: str) -> None: ...
    def removeItem(self, key: str) -> None: ...
    def clear(self) -> None: ...

class Console(Protocol):
    """Protocol for the Console object (window.console)."""
    def log(self, *args: Any) -> None: ...
    def warn(self, *args: Any) -> None: ...
    def error(self, *args: Any) -> None: ...
    def info(self, *args: Any) -> None: ...
    def debug(self, *args: Any) -> None: ...
    def trace(self, *args: Any) -> None: ...
    def dir(self, obj: Any, options: Any = None) -> None: ...
    def dirxml(self, *args: Any) -> None: ...
    def table(self, data: Any, columns: list[str] | None = None) -> None: ...
    def count(self, label: str = "") -> None: ...
    def countReset(self, label: str = "") -> None: ...
    def group(self, *args: Any) -> None: ...
    def groupCollapsed(self, *args: Any) -> None: ...
    def groupEnd(self) -> None: ...
    def time(self, label: str = "") -> None: ...
    def timeLog(self, label: str = "", *args: Any) -> None: ...
    def timeEnd(self, label: str = "") -> None: ...
    def clear(self) -> None: ...
    # assert_ maps to console.assert in JS (avoids the Python keyword)
    def assert_(self, condition: bool, *args: Any) -> None: ...
    def profile(self, label: str = "") -> None: ...
    def profileEnd(self, label: str = "") -> None: ...

class Performance(Protocol):
    """Protocol for the Performance object."""
    @property
    def timeOrigin(self) -> float: ...
    @property
    def timing(self) -> Any: ...
    @property
    def navigation(self) -> Any: ...
    def now(self) -> float: ...
    def mark(self, name: str, markOptions: Any = None) -> Any: ...
    def measure(self, measureName: str, startOrMeasureOptions: Any = None, endMark: str = "") -> Any: ...
    def clearMarks(self, name: str = "") -> None: ...
    def clearMeasures(self, name: str = "") -> None: ...
    def getEntries(self) -> Any: ...
    def getEntriesByName(self, name: str, type: str = "") -> Any: ...
    def getEntriesByType(self, type: str) -> Any: ...

class Crypto(Protocol):
    """Protocol for the Crypto object."""
    @property
    def subtle(self) -> Any: ...
    def getRandomValues(self, array: Any) -> Any: ...
    def randomUUID(self) -> str: ...

class CustomElementRegistry(Protocol):
    """Protocol for CustomElementRegistry."""
    def define(self, name: str, constructor: Any, options: Any = None) -> None: ...
    def get(self, name: str) -> Any: ...
    def getName(self, constructor: Any) -> str | None: ...
    def whenDefined(self, name: str) -> Any: ...
    def upgrade(self, root: Any) -> None: ...

class Navigator(Protocol):
    """Protocol for the browser's Navigator object."""
    @property
    def userAgent(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def languages(self) -> list[str]: ...
    @property
    def platform(self) -> str: ...
    @property
    def vendor(self) -> str: ...
    @property
    def cookieEnabled(self) -> bool: ...
    @property
    def onLine(self) -> bool: ...
    @property
    def maxTouchPoints(self) -> int: ...
    @property
    def hardwareConcurrency(self) -> int: ...
    @property
    def deviceMemory(self) -> float: ...
    @property
    def pdfViewerEnabled(self) -> bool: ...
    @property
    def webdriver(self) -> bool: ...
    @property
    def clipboard(self) -> Any: ...
    @property
    def credentials(self) -> Any: ...
    @property
    def geolocation(self) -> Any: ...
    @property
    def mediaDevices(self) -> Any: ...
    @property
    def permissions(self) -> Any: ...
    @property
    def serviceWorker(self) -> Any: ...
    @property
    def storage(self) -> Any: ...
    @property
    def locks(self) -> Any: ...
    @property
    def mediaCapabilities(self) -> Any: ...
    @property
    def connection(self) -> Any: ...
    
    def sendBeacon(self, url: str, data: Any = None) -> bool: ...
    def vibrate(self, pattern: Any) -> bool: ...
    def share(self, data: Any = None) -> Any: ...
    def canShare(self, data: Any = None) -> bool: ...
    def getBattery(self) -> Any: ...
    def getGamepads(self) -> Any: ...
    def requestMediaKeySystemAccess(self, keySystem: str, supportedConfigurations: Any) -> Any: ...
    def registerProtocolHandler(self, scheme: str, url: str) -> None: ...

class Document(Protocol):
    """Protocol for the browser's Document object model."""
    @property
    def body(self) -> DOMElement: ...
    @property
    def head(self) -> DOMElement: ...
    @property
    def title(self) -> str: ...
    @title.setter
    def title(self, value: str) -> None: ...
    @property
    def documentElement(self) -> DOMElement: ...
    @property
    def activeElement(self) -> DOMElement | None: ...
    @property
    def fullscreenElement(self) -> DOMElement | None: ...
    @property
    def pointerLockElement(self) -> DOMElement | None: ...
    @property
    def readyState(self) -> str: ...
    @property
    def referrer(self) -> str: ...
    @property
    def URL(self) -> str: ...
    @property
    def domain(self) -> str: ...
    @property
    def cookie(self) -> str: ...
    @cookie.setter
    def cookie(self, value: str) -> None: ...
    @property
    def lastModified(self) -> str: ...
    @property
    def characterSet(self) -> str: ...
    @property
    def contentType(self) -> str: ...
    @property
    def doctype(self) -> Any: ...
    @property
    def forms(self) -> Any: ...
    @property
    def images(self) -> Any: ...
    @property
    def links(self) -> Any: ...
    @property
    def scripts(self) -> Any: ...
    @property
    def styleSheets(self) -> Any: ...
    @property
    def visibilityState(self) -> str: ...
    @property
    def hidden(self) -> bool: ...
    @property
    def designMode(self) -> str: ...
    @designMode.setter
    def designMode(self, value: str) -> None: ...
    @property
    def dir(self) -> str: ...
    @dir.setter
    def dir(self, value: str) -> None: ...

    def getElementById(self, id: str) -> DOMElement | None: ...
    def getElementsByClassName(self, classNames: str) -> Any: ...
    def getElementsByTagName(self, tagName: str) -> Any: ...
    def getElementsByName(self, elementName: str) -> Any: ...
    def querySelector(self, selectors: str) -> DOMElement | None: ...
    def querySelectorAll(self, selectors: str) -> Any: ...
    def createElement(self, tag: str) -> DOMElement: ...
    def createTextNode(self, text: str) -> DOMTextNode: ...
    def createDocumentFragment(self) -> Any: ...
    def createComment(self, data: str) -> Any: ...
    def createEvent(self, type: str) -> Any: ...
    def createRange(self) -> Any: ...
    def adoptNode(self, externalNode: Any) -> Any: ...
    def importNode(self, externalNode: Any, deep: bool = False) -> Any: ...
    def write(self, *text: str) -> None: ...
    def writeln(self, *text: str) -> None: ...
    def open(self) -> Any: ...
    def close(self) -> None: ...
    def hasFocus(self) -> bool: ...
    def getSelection(self) -> Any: ...
    def elementFromPoint(self, x: float, y: float) -> DOMElement | None: ...
    def elementsFromPoint(self, x: float, y: float) -> Any: ...
    def exitFullscreen(self) -> Any: ...
    def exitPointerLock(self) -> None: ...
    def execCommand(self, commandId: str, showUI: bool = False, value: str = "") -> bool: ...
    def queryCommandEnabled(self, commandId: str) -> bool: ...
    def queryCommandState(self, commandId: str) -> bool: ...
    def queryCommandValue(self, commandId: str) -> str: ...

    def addEventListener(self, event: str, callback: Any) -> None: ...
    def removeEventListener(self, event: str, callback: Any) -> None: ...
    def dispatchEvent(self, event: Any) -> bool: ...

class WindowLocation(Protocol):
    """Protocol for window.location."""
    @property
    def href(self) -> str: ...
    @href.setter
    def href(self, value: str) -> None: ...
    @property
    def pathname(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def hostname(self) -> str: ...
    @property
    def port(self) -> str: ...
    @property
    def protocol(self) -> str: ...
    @property
    def search(self) -> str: ...
    @property
    def hash(self) -> str: ...
    @property
    def origin(self) -> str: ...

    def assign(self, url: str) -> None: ...
    def reload(self) -> None: ...
    def replace(self, url: str) -> None: ...
    def toString(self) -> str: ...

class WindowHistory(Protocol):
    """Protocol for window.history."""
    @property
    def length(self) -> int: ...
    @property
    def scrollRestoration(self) -> str: ...
    @property
    def state(self) -> Any: ...

    def back(self) -> None: ...
    def forward(self) -> None: ...
    def go(self, delta: int) -> None: ...
    def pushState(self, data: Any, title: str, url: str) -> None: ...
    def replaceState(self, data: Any, title: str, url: str) -> None: ...

class ScrollToOptions(TypedDict, total=False):
    """Options for scroll movement."""
    top: float
    left: float
    behavior: Literal["auto", "smooth", "instant"]

class Window(Protocol):
    """Comprehensive protocol for the Window object (browser window)."""
    @property
    def document(self) -> Document: ...
    @property
    def location(self) -> WindowLocation: ...
    @property
    def history(self) -> WindowHistory: ...
    @property
    def navigator(self) -> Navigator: ...
    @property
    def screen(self) -> Screen: ...
    @property
    def performance(self) -> Performance: ...
    @property
    def localStorage(self) -> Storage: ...
    @property
    def sessionStorage(self) -> Storage: ...
    @property
    def console(self) -> Console: ...
    @property
    def crypto(self) -> Crypto: ...
    @property
    def customElements(self) -> CustomElementRegistry: ...
    @property
    def visualViewport(self) -> VisualViewport | None: ...

    @property
    def innerWidth(self) -> int: ...
    @property
    def innerHeight(self) -> int: ...
    @property
    def outerWidth(self) -> int: ...
    @property
    def outerHeight(self) -> int: ...
    @property
    def screenX(self) -> int: ...
    @property
    def screenY(self) -> int: ...
    @property
    def screenLeft(self) -> int: ...
    @property
    def screenTop(self) -> int: ...
    @property
    def scrollX(self) -> float: ...
    @property
    def scrollY(self) -> float: ...
    @property
    def pageXOffset(self) -> float: ...
    @property
    def pageYOffset(self) -> float: ...
    @property
    def devicePixelRatio(self) -> float: ...
    
    @property
    def frameElement(self) -> DOMElement | None: ...
    @property
    def frames(self) -> Window: ...
    @property
    def length(self) -> int: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def opener(self) -> Any: ...
    @property
    def parent(self) -> Window: ...
    # self_ maps to window.self in JS (avoids the Python keyword)
    @property
    def self_(self) -> Window: ...
    @property
    def top(self) -> Window | None: ...
    
    @property
    def closed(self) -> bool: ...
    @property
    def isSecureContext(self) -> bool: ...
    @property
    def origin(self) -> str: ...
    @property
    def crossOriginIsolated(self) -> bool: ...

    def alert(self, message: str = "") -> None: ...
    def confirm(self, message: str = "") -> bool: ...
    def prompt(self, message: str = "", default: str = "") -> str | None: ...
    def open(self, url: str = "", target: str = "_blank", features: str = "") -> Window | None: ...
    def close(self) -> None: ...
    def stop(self) -> None: ...
    def focus(self) -> None: ...
    def blur(self) -> None: ...
    # print_ maps to window.print in JS
    def print_(self) -> None: ...
    def postMessage(self, message: Any, targetOrigin: str, transfer: Any = None) -> None: ...

    def requestAnimationFrame(self, callback: Any) -> int: ...
    def cancelAnimationFrame(self, handle: int) -> None: ...
    def setTimeout(self, callback: Any, delay: int = 0, *args: Any) -> int: ...
    def clearTimeout(self, handle: int) -> None: ...
    def setInterval(self, callback: Any, delay: int = 0, *args: Any) -> int: ...
    def clearInterval(self, handle: int) -> None: ...
    def queueMicrotask(self, callback: Any) -> None: ...
    
    def fetch(self, resource: Any, options: Any = None) -> Any: ...
    def atob(self, data: str) -> str: ...
    def btoa(self, data: str) -> str: ...
    
    def getComputedStyle(self, element: Any, pseudoElt: str | None = None) -> Any: ...
    def matchMedia(self, query: str) -> MediaQueryList: ...
    def requestIdleCallback(self, callback: Any, options: Any = None) -> int: ...
    def cancelIdleCallback(self, handle: int) -> None: ...
    def getSelection(self) -> Any: ...
    def structuredClone(self, value: Any, options: Any = None) -> Any: ...
    def createImageBitmap(self, image: Any, options: Any = None) -> Any: ...

    def addEventListener(self, event: str, callback: Any) -> None: ...
    def removeEventListener(self, event: str, callback: Any) -> None: ...

    @overload
    def scrollTo(self, x: float, y: float) -> None: ...
    @overload
    def scrollTo(self, options: ScrollToOptions) -> None: ...
    def scrollTo(self, *args: Any, **kwargs: Any) -> None: ...

    @overload
    def scrollBy(self, x: float, y: float) -> None: ...
    @overload
    def scrollBy(self, options: ScrollToOptions) -> None: ...
    def scrollBy(self, *args: Any, **kwargs: Any) -> None: ...

    @overload
    def scroll(self, x: float, y: float) -> None: ...
    @overload
    def scroll(self, options: ScrollToOptions) -> None: ...
    def scroll(self, *args: Any, **kwargs: Any) -> None: ...


class _JSON(Protocol):
    """Protocol for the global JSON object."""
    def parse(self, text: str) -> Any: ...

class JS(Protocol):
    """Protocol for the JS global (root) scope."""
    @property
    def document(self) -> Document: ...
    @property
    def window(self) -> Window: ...
    @property
    def console(self) -> Console: ...
    @property
    def JSON(self) -> _JSON: ...
    
    def queueMicrotask(self, callback: Any) -> None: ...
