"""
PyOn-Py Dev Server

Features:
- Static file serving (required because browser cannot fetch via file://)
- Auto-generate /loader.js containing a list of all .py files in the project
- Hot reload via SSE — browser refreshes automatically when .py files change

To run from the pyon-py/ folder:
    python dev/server.py

Then open http://localhost:8000
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

from aiohttp import web
from watchfiles import awatch

import pyon

HOST = "localhost"
PORT = 8000

PROJECT_ROOT = Path.cwd()

IGNORED_DIRS = {"__pycache__", ".git", "node_modules", "dev", "tests", "venv", "cli"}

PYODIDE_VERSION = "314.0.2"
PYODIDE_CDN = f"https://cdn.jsdelivr.net/pyodide/v{PYODIDE_VERSION}/full/pyodide.js"

_sse_clients: set[web.StreamResponse] = set()


# ---------------------------------------------------------------------------
# File scanner — collect all .py files in the correct order
# ---------------------------------------------------------------------------

PYON_PKG_DIR = Path(pyon.__file__).resolve().parent


def _collect_py_files() -> list[str]:
    """
    Recursively scan the framework and PROJECT_ROOT, and return a list of .py paths.
    """
    buckets: list[Path] = []

    # 1. Collect framework files from site-packages or src
    for path in sorted(PYON_PKG_DIR.rglob("*.py")):
        if any(part in IGNORED_DIRS for part in path.parts):
            continue
        buckets.append(path.relative_to(PYON_PKG_DIR.parent))

    # 2. Collect user files
    for path in sorted(PROJECT_ROOT.rglob("*.py")):
        # Skip ignored folders
        if any(part in IGNORED_DIRS for part in path.parts):
            continue

        rel = path.relative_to(PROJECT_ROOT)

        # This prevents duplicate entries if the dev server is running from the framework repo itself
        if rel.parts[0] == "pyon":
            continue

        buckets.append(rel)

    # Sort by length, then by whether it's an __init__.py file, and finally by path
    def sort_key(p: Path) -> tuple:
        is_init = 0 if p.name == "__init__.py" else 1
        return (len(p.parts), is_init, str(p))

    buckets.sort(key=sort_key)

    result = [str(p).replace("\\", "/") for p in buckets]

    return result


# ---------------------------------------------------------------------------
# Generate loader.js
# ---------------------------------------------------------------------------


def _generate_loader_js() -> str:
    """
    Generate loader.js dynamically based on the .py files in the project.
    Called every time the browser requests /loader.js.
    """
    py_files = _collect_py_files()
    files_json = json.dumps(py_files, indent=4)

    return f"""\
// loader.js — AUTO-GENERATED by dev/server.py
// Do not edit manually — will be overwritten each time the server restarts or a file changes

const PYODIDE_VERSION = "{PYODIDE_VERSION}";
const PY_FILES = {files_json};

async function initPyOnPy() {{
    const status = document.getElementById("pyon-py-status");
    const setStatus = (msg) => {{ if (status) status.textContent = msg; }};

    try {{
        setStatus("Loading Pyodide " + PYODIDE_VERSION + "...");
        window.__pyodide = await loadPyodide();
        window.__pyodide.setDebug(true);
        window.__pyodide.runPython('import os; os.environ["PYON_ENV"] = "development"');

        // Add root virtual FS to sys.path
        window.__pyodide.runPython(`
import sys
sys.path.insert(0, "/")
`);

        // Install third-party dependencies for the client (Browser)
        setStatus("Installing PIP dependencies...");
        await window.__pyodide.loadPackage("micropip");
        const micropip = window.__pyodide.pyimport("micropip");
        await micropip.install(["typing-extensions"]);

        // Fetch all Python files and write them to the virtual FS Pyodide
        setStatus("Loading Python files...");
        for (const filePath of PY_FILES) {{
            await fetchAndWriteFile(filePath);
        }}

        // Mount app
        setStatus("Rendering components...");
        await runApp();

        setStatus("");
        if (status) status.remove();

    }} catch (err) {{
        if (status) {{
            status.textContent = "Error: " + err.message;
            status.style.color = "red";
        }}
        console.error("[PyOnPy] Error:", err);
    }}
}}

async function fetchAndWriteFile(filePath) {{
    // Add ?t=... to cache-bust the browser to avoid loading an old version
    const res = await fetch("/" + filePath + "?t=" + Date.now());
    if (!res.ok) throw new Error(`Gagal fetch ${{filePath}}: ${{res.status}}`);
    const code = await res.text();

    // Create the directory in the virtual FS if it doesn't exist
    const parts = filePath.split("/");
    if (parts.length > 1) {{
        const dir = parts.slice(0, -1).join("/");
        window.__pyodide.FS.mkdirTree(dir);
    }}

    window.__pyodide.FS.writeFile(filePath, code);
}}

async function runApp() {{
    // Clear the DOM
    const appEl = document.getElementById("app");
    if (appEl) appEl.innerHTML = "";
    
    // Teardown framework state if it was already running
    window.__pyodide.runPython(`
try:
    from pyon.core import teardown
    teardown()
except ImportError:
    pass
`);

    // Run the application again
    await window.__pyodide.runPythonAsync(`
from app import start
start()
`);
}}

async function restart(changedFiles) {{
    console.log("[PyOnPy] Hot Reloading:", changedFiles);
    
    // 1. Re-fetch only the changed files
    for (const filePath of changedFiles) {{
        await fetchAndWriteFile(filePath);
    }}

    // 2. Invalidate all project modules (app, pyon, src) from the cache 
    // so that the dependency tree is re-evaluated with freshness
    window.__pyodide.runPython(`
import sys

project_namespaces = ("app", "pyon", "src")
to_delete = [k for k in sys.modules if k.startswith(project_namespaces)]
for k in to_delete:
    del sys.modules[k]
`);

    // 3. Re-run the application
    await runApp();
}}

// Hot reload via SSE (browser refreshes automatically)
const _sse = new EventSource("/__reload");
_sse.addEventListener("message", async (e) => {{
    const data = JSON.parse(e.data);
    if (data.type === "reload") {{
        // Fallback for older versions
        location.reload();
    }} else if (data.type === "update") {{
        await restart(data.files);
    }}
}});
_sse.addEventListener("error", () => {{
    // SSE is down — try reconnecting automatically
}});

initPyOnPy();
"""


# ---------------------------------------------------------------------------
# HTTP handlers
# ---------------------------------------------------------------------------


async def handle_loader_js(request: web.Request) -> web.Response:
    """Generate loader.js on-the-fly each time a request is made."""
    content = _generate_loader_js()
    return web.Response(
        text=content,
        content_type="application/javascript",
        headers={"Cache-Control": "no-store"},
    )


async def handle_sse(request: web.Request) -> web.StreamResponse:
    """SSE endpoint — browser subscribes to receive reload notifications."""
    response = web.StreamResponse(
        headers={
            "Content-Type": "text/event-stream",
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        }
    )
    await response.prepare(request)
    _sse_clients.add(response)

    # Send initial ping to let the browser know the connection is successful
    await response.write(b'data: {"type": "connected"}\n\n')

    try:
        # Hold the connection until the client disconnects
        await asyncio.sleep(float("inf"))
    except (asyncio.CancelledError, ConnectionResetError):
        pass
    finally:
        _sse_clients.discard(response)

    return response


async def handle_static(request: web.Request) -> web.Response | web.FileResponse:
    """Serve static files from PROJECT_ROOT."""
    rel_path = request.match_info.get("path", "index.html") or "index.html"
    project_root = PROJECT_ROOT.resolve()

    # Security: prevent path traversal (../../etc)
    try:
        target = (PROJECT_ROOT / rel_path).resolve()
        target.relative_to(project_root)
    except ValueError:
        return web.Response(status=403, text="Forbidden")

    if target.is_dir():
        target = target / "index.html"

    if not target.exists():
        target = project_root / "index.html"

        if not target.exists():
            return web.Response(status=404, text="index.html not found")

    return web.FileResponse(target)


# ---------------------------------------------------------------------------
# File watcher — broadcast reload to all browser tabs
# ---------------------------------------------------------------------------


async def _broadcast(event: dict) -> None:
    payload = ("data: " + json.dumps(event) + "\n\n").encode()
    dead: set[web.StreamResponse] = set()

    for client in list(_sse_clients):
        try:
            await client.write(payload)
        except Exception:
            dead.add(client)

    _sse_clients.difference_update(dead)


async def watch_files() -> None:
    """Watch PROJECT_ROOT (dan framework) for changes to .py files."""
    watch_paths = [PROJECT_ROOT]

    # Only watch PYON_PKG_DIR if it's outside PROJECT_ROOT
    if PROJECT_ROOT not in PYON_PKG_DIR.parents and PROJECT_ROOT != PYON_PKG_DIR:
        watch_paths.append(PYON_PKG_DIR)
        print(f"  Watching: {PROJECT_ROOT} and {PYON_PKG_DIR}")
    else:
        print(f"  Watching: {PROJECT_ROOT}")

    async for changes in awatch(*watch_paths):
        changed_py_files = []
        for _, path in changes:
            p = Path(path)
            if p.suffix == ".py":
                # Find relative path that matches browser
                try:
                    rel = str(p.relative_to(PROJECT_ROOT))
                except ValueError:
                    try:
                        rel = str(p.relative_to(PYON_PKG_DIR.parent))
                    except ValueError:
                        continue

                # Cek ignores
                if rel.startswith("pyon/") or not any(
                    ignored in Path(rel).parts for ignored in IGNORED_DIRS
                ):
                    print(f"  changed : {rel}")
                    changed_py_files.append(rel.replace("\\", "/"))

        if changed_py_files:
            await _broadcast({"type": "update", "files": changed_py_files})


async def handle_pyon_framework(
    request: web.Request,
) -> web.Response | web.FileResponse:
    """Serve internal framework PyOn-Py directly from site-packages"""
    rel_path = request.match_info.get("path", "")
    target = (PYON_PKG_DIR / rel_path).resolve()

    # Security: prevent path traversal (../../etc)
    try:
        target.relative_to(PYON_PKG_DIR)
    except ValueError:
        return web.Response(status=403, text="Forbidden")

    if not target.exists() or target.is_dir():
        return web.Response(status=404, text="Framework file not found")

    return web.FileResponse(target)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


async def main() -> None:
    app = web.Application()
    app.router.add_get("/loader.js", handle_loader_js)
    app.router.add_get("/__reload", handle_sse)
    app.router.add_get("/pyon/{path:.+}", handle_pyon_framework)
    app.router.add_get("/", handle_static)
    app.router.add_get("/{path:.+}", handle_static)

    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, HOST, PORT)
    await site.start()

    print(f"\nPyOn-Py dev server running at http://{HOST}:{PORT}")
    print(f"Pyodide version : {PYODIDE_VERSION}")

    # Display the files that will be loaded
    files = _collect_py_files()
    print(f"\nFiles to be loaded ({len(files)} file):")
    for f in files:
        print(f"  {f}")
    print()

    await watch_files()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nServer stopped.")
        sys.exit(0)
