"""Virtual DOM Diffing Module — core algorithm for calculating minimum changes.

This module contains the diff algorithm that compares two VNode trees (old vs new)
and produces a list of Patches — minimal instructions to update the DOM from the
old state to the new state.

Runtime usage flow:
    App._update_from_key()  →  diff(old_tree, new_tree)  →  list[Patch]
                                                                ↓
    bridge.apply_patches()  →  _apply_single_patch()     →  DOM update

Path format:
    The path uses a dot-separated index format representing the position
    of the node within the tree. Example:
    - ``"0"``       → root node
    - ``"0.1"``     → 1st child of root
    - ``"0.1.3"``   → 3rd child of the 1st child of root
"""

from __future__ import annotations
from typing import Optional, Literal, TypedDict, Union, cast
from .vnode import VNode, Props


# =============================================================================
# Patch operation types
# =============================================================================
# These patch types represent DOM modification instructions.
# Generated by diff() and consumed by _apply_single_patch()
# in bridge/impl/pyodide_impl.py.

class CreatePatch(TypedDict):
    """Instruction to create a new DOM element.

    Generated by ``diff()`` when a new node appears (old=None, new=VNode).

    Attributes:
        op: Always ``"CREATE"``.
        path: DOM path where the new element will be created.
            Example: ``"0.2"`` — 2nd child of root.
        node: VNode to be converted into a new DOM element.
    """

    op: Literal["CREATE"]
    path: str
    node: "VNode"


class RemovePatch(TypedDict):
    """Instruction to remove a DOM element.

    Generated by ``diff()`` when an old node is removed (old=VNode, new=None).

    Attributes:
        op: Always ``"REMOVE"``.
        path: DOM path of the element to be removed.
            Example: ``"0.1.3"``
    """

    op: Literal["REMOVE"]
    path: str


class ReplacePatch(TypedDict):
    """Instruction to replace a DOM element entirely.

    Generated by ``diff()`` when the tag type changes (for example
    ``"div"`` → ``"span"``), requiring the entire subtree to be replaced.

    Attributes:
        op: Always ``"REPLACE"``.
        path: DOM path of the element to be replaced.
        node: The new VNode that will replace the old element.
    """

    op: Literal["REPLACE"]
    path: str
    node: "VNode"


class UpdatePropsPatch(TypedDict):
    """Instruction to update props/attributes on an existing DOM element.

    Generated by ``diff()`` when the tag is the same but props change.
    Props with a value of ``None`` mean the prop is removed.

    Attributes:
        op: Always ``"UPDATE_PROPS"``.
        path: DOM path of the target element.
        props: Dictionary containing the changed props.
            Example: ``{"class": "active", "disabled": None}``
            (``None`` = remove the ``disabled`` prop).
    """

    op: Literal["UPDATE_PROPS"]
    path: str
    props: "Props"


class SetTextPatch(TypedDict):
    """Instruction to change the text content of a DOM element.

    Generated by ``diff()`` when both nodes have a single child
    that is text, and the text differs.

    Attributes:
        op: Always ``"SET_TEXT"``.
        path: DOM path of the target element.
        text: The new text content.
    """

    op: Literal["SET_TEXT"]
    path: str
    text: str


class ReorderChildrenPatch(TypedDict):
    """Instruction to reorder the child nodes of a DOM element.

    Generated by ``diff()`` when the structure of children changes (order,
    addition, or removal). This patch replaces individual CREATE/REMOVE
    mechanisms for efficiency — a single reorder operation handles
    all child changes at once.

    Attributes:
        op: Always ``"REORDER_CHILDREN"``.
        path: DOM path of the parent element whose children will be reordered.
        mapping: List representing the new order of children.
            Each item can be:
            - ``int`` → reuse the old child at that index.
            - ``VNode`` → create a new DOM element from this VNode.
            - ``str | int | float`` → create a new text node.
            Example: ``[1, 0, VNode(...)]`` = old child #1, then #0,
            then a new element.
    """

    op: Literal["REORDER_CHILDREN"]
    path: str
    mapping: list[Union[int, "VNode", str, float]]


# Union type of all Patches — used as parameter/return types.
Patch = CreatePatch | RemovePatch | ReplacePatch | UpdatePropsPatch | SetTextPatch | ReorderChildrenPatch


# =============================================================================
# Factory functions for Patch creation
# =============================================================================
# These helper functions are used internally by diff()
# to create Patch instances in a more concise way.

def create_patch(path: str, node: "VNode") -> CreatePatch:
    """Create a CreatePatch to add a new element.

    Args:
        path: DOM path where the new element will be created. Example: ``"0.2"``.
        node: VNode to be converted into a DOM element.

    Returns:
        CreatePatch dict with op="CREATE".
    """
    return CreatePatch(op="CREATE", path=path, node=node)


def remove_patch(path: str) -> RemovePatch:
    """Create a RemovePatch to remove an element.

    Args:
        path: DOM path of the element to be removed. Example: ``"0.1.3"``.

    Returns:
        RemovePatch dict with op="REMOVE".
    """
    return RemovePatch(op="REMOVE", path=path)


def replace_patch(path: str, node: "VNode") -> ReplacePatch:
    """Create a ReplacePatch to replace an element entirely.

    Args:
        path: DOM path of the element to be replaced. Example: ``"0.1"``.
        node: The new VNode replacing the old element.

    Returns:
        ReplacePatch dict with op="REPLACE".
    """
    return ReplacePatch(op="REPLACE", path=path, node=node)


def update_props_patch(path: str, props: "Props") -> UpdatePropsPatch:
    """Create an UpdatePropsPatch to update element props.

    Args:
        path: DOM path of the target element. Example: ``"0.1.0"``.
        props: Dictionary containing the changed props.
            Example: ``{"class": "new-class", "hidden": None}``.

    Returns:
        UpdatePropsPatch dict with op="UPDATE_PROPS".
    """
    return UpdatePropsPatch(op="UPDATE_PROPS", path=path, props=props)


def set_text_patch(path: str, text: str) -> SetTextPatch:
    """Create a SetTextPatch to change the text content of an element.

    Args:
        path: DOM path of the target element. Example: ``"0.0.1"``.
        text: The new text content.

    Returns:
        SetTextPatch dict with op="SET_TEXT".
    """
    return SetTextPatch(op="SET_TEXT", path=path, text=text)


def reorder_children_patch(path: str, mapping: list[Union[int, "VNode", str, float]]) -> ReorderChildrenPatch:
    """Create a ReorderChildrenPatch to reorder children.

    Args:
        path: DOM path of the parent element. Example: ``"0.1"``.
        mapping: List representing the new child order. See the
            ``ReorderChildrenPatch`` docstring for format details.

    Returns:
        ReorderChildrenPatch dict with op="REORDER_CHILDREN".
    """
    return ReorderChildrenPatch(op="REORDER_CHILDREN", path=path, mapping=mapping)


# =============================================================================
# Helper functions
# =============================================================================

def _is_text(value: object) -> bool:
    """Check if the value is of text/primitive type (string, int, or float).

    Used by ``diff()`` to detect text nodes among children.
    Text nodes are not diffed recursively — only their text content is
    compared.

    Args:
        value: The value to be checked.

    Returns:
        ``True`` if the value is a ``str``, ``int``, or ``float``.
    """
    return isinstance(value, (str, int, float))


def _diff_props(old: "Props", new: "Props") -> "Props":
    """Compare two props dictionaries and return the changed ones.

    Compares each key from both dicts. Props that are changed or
    added will be included in the result. Props present in ``old`` but missing
    in ``new`` are marked with a value of ``None`` (instruction to remove).

    Event handlers (callables) are filtered out by the caller (``diff()``) because
    Python callables cannot be reliably compared with ``==``.

    Called by:
        - ``diff()`` — in case 5 (props changed) to compute the delta.

    Args:
        old: Old props dictionary.
            Example: ``{"class": "btn", "disabled": True}``
        new: New props dictionary.
            Example: ``{"class": "btn active"}``

    Returns:
        Dictionary containing changed props. A ``None`` value indicates
        a removed prop.
        Example: ``{"class": "btn active", "disabled": None}``
    """
    changes: "Props" = {}
    all_keys = set(old) | set(new)
    for key in all_keys:
        old_val = old.get(key)
        new_val = new.get(key)
        if old_val != new_val:
            # None means the prop is removed (present in old, missing in new)
            changes[key] = new_val
    return changes


# =============================================================================
# Core diff algorithm
# =============================================================================

def diff(
    old: Optional["VNode"],
    new: Optional["VNode"],
    path: str = "0",
) -> list[Patch]:
    """Virtual DOM diffing algorithm — compare two VNode trees and generate Patches.

    This function recursively compares the old VNode tree (``old``) with the new VNode tree (``new``)
    and generates a minimal list of Patches needed to transform the DOM from the old
    state to the new state.

    The algorithm handles 7 cases:
        1. Both are ``None`` → no change (returns empty list).
        2. ``new`` is ``None`` → node removed → ``REMOVE``.
        3. ``old`` is ``None`` → new node appears → ``CREATE``.
        4. Tag changes (``old.tag != new.tag``) → replace subtree → ``REPLACE``.
        5. Props change → ``UPDATE_PROPS`` (callables/event handlers are skipped).
        6. Text content changes (single primitive child) → ``SET_TEXT``.
        7. Children change → array reconciliation with keyed matching →
           ``REORDER_CHILDREN`` + recursive diff per child.

    Keyed reconciliation (case 7):
        - First, try to match the new child with the old child based on
          ``VNode.key`` (keyed matching). This ensures components with the same key
          are recognized even if their positions shift.
        - If there is no key, fallback to matching based on index
          (only if the tag is the same).
        - Children that do not match are treated as new elements.
        - The matching result is stored in a ``mapping`` used by
          ``REORDER_CHILDREN``.

    Called by:
        - ``App._update_from_key()`` in ``core/app.py`` — to calculate
          patches between the old branch and the new branch during incremental updates.

    Args:
        old: Old VNode tree (current state). ``None`` if the node does not exist yet.
        new: New VNode tree (desired state). ``None`` if the node is removed.
        path: Current DOM path. Default ``"0"`` (root).
            Example: ``"0.1.3"`` for the 3rd child of the 1st child.

    Returns:
        List of Patches that need to be applied to the DOM. Can contain a combination
        of ``CREATE``, ``REMOVE``, ``REPLACE``, ``UPDATE_PROPS``,
        ``SET_TEXT``, and ``REORDER_CHILDREN``.
        An empty list if there are no changes.
    """
    patches: list[Patch] = []

    # ── Case 1: both are None — no changes ─────────────────────────────
    if old is None and new is None:
        return []

    # ── Case 2: old node removed (new=None) ────────────────────────────
    if new is None:
        return [remove_patch(path)]

    # ── Case 3: new node appears (old=None) ─────────────────────────────
    if old is None:
        return [create_patch(path, new)]

    # ── Case 4: tag type changed — replace the entire subtree ──────────────
    if old.tag != new.tag:
        return [replace_patch(path, new)] 

    # ── Case 5: props changed ───────────────────────────────────────────
    prop_changes = _diff_props(old.props, new.props)
    # Filter out event handlers (callables) because Python callables cannot
    # be reliably compared using ==. Event handlers are always rebound
    # when the element is rebuilt via _build_dom_element().
    filtered: "Props" = {k: v for k, v in prop_changes.items() if not callable(v)}
    if filtered:
        patches.append(UpdatePropsPatch(op="UPDATE_PROPS", path=path, props=filtered))

    # ── Case 6: text content changed (single primitive child) ─────────────
    old_is_text = len(old.children) == 1 and _is_text(old.children[0])
    new_is_text = len(new.children) == 1 and _is_text(new.children[0])
    if old_is_text and new_is_text and old.children[0] != new.children[0]:
        patches.append(SetTextPatch(op="SET_TEXT", path=path, text=str(new.children[0])))
        return patches

    # ── Case 7: diff children — array reconciliation (Keyed) ────────────
    # mapping represents the order of new children:
    # - int          → reuse old child at that index
    # - VNode/text   → create a new element
    mapping: list[Union[int, VNode, str, float]] = []

    # Build key → index map of old children for O(1) keyed lookup
    old_key_map = {
        c.key: i for i, c in enumerate(old.children) 
        if isinstance(c, VNode) and c.key is not None
    }
    
    # Track old indices already used to prevent duplicate reuse
    used_old_indices = set()
    # Patches for changes inside matched children
    child_patches: list[Patch] = []
    
    for i, new_child in enumerate(new.children):
        matched_old_index = None
        
        if isinstance(new_child, VNode):
            # Strategy 1: Keyed matching — match based on VNode.key
            if new_child.key is not None and new_child.key in old_key_map:
                matched_old_index = old_key_map[new_child.key]
            else:
                # Strategy 2: Fallback index matching — match based on
                # position (only if tags are identical and both have no key)
                if i < len(old.children):
                    old_c = old.children[i]
                    if isinstance(old_c, VNode) and old_c.key is None and old_c.tag == new_child.tag:
        
                        matched_old_index = i
        else:
            # Text node: fallback match based on position
            if i < len(old.children) and _is_text(old.children[i]):
                matched_old_index = i
                
        if matched_old_index is not None and matched_old_index not in used_old_indices:
            # Old child found — reuse (record index in mapping)
            mapping.append(matched_old_index)
            used_old_indices.add(matched_old_index)
            old_child_matched = old.children[matched_old_index]
            
            if _is_text(old_child_matched) and _is_text(new_child):
                # Both children are text — compare their contents
                if old_child_matched != new_child:
                    child_patches.append(set_text_patch(f"{path}.{i}", str(new_child)))
            else:
                # Both children are VNodes — diff recursively
                child_patches += diff(cast("VNode", old_child_matched), cast("VNode", new_child), f"{path}.{i}")
        else:
            # No matching old child — this is a new element
            mapping.append(new_child)
            
    # Check if the structure of children is identical (same order and count).
    # If identical, REORDER_CHILDREN is not needed — only child_patches
    # need to be applied (UPDATE_PROPS, SET_TEXT, etc., within the child).
    is_structurally_identical = (
        len(old.children) == len(new.children) 
        and all(isinstance(m, int) and m == i for i, m in enumerate(mapping))
    )
    
    if not is_structurally_identical:
        # Structure changed — add reorder instruction
        patches.append(reorder_children_patch(path, mapping))
        
    # Merge patches from changes inside children
    patches += child_patches
    return patches